#!/bin/bash

# Использование:
# ./scripts/generate_constants.sh path/to/input.toml path/to/output.go

TOML_FILE="$1"
OUTPUT_FILE="$2"

if [ -z "$TOML_FILE" ] || [ -z "$OUTPUT_FILE" ]; then
  echo "Usage: $0 path/to/file.toml path/to/output.go"
  exit 1
fi

{
  echo "//go:generate bash ./generate_constants.sh ./locales/ru.toml ./i18n_consts.go"
  echo "// Code generated by generate_constants.sh. DO NOT EDIT."
  echo
  echo "package replyme"
  echo
  echo "const ("

  # Используем grep + cut + tr для извлечения значения
  grep '^\s*id\s*=' "$TOML_FILE" | while read -r line; do
    id=$(echo "$line" | cut -d '"' -f2)
    const_name=$(echo "i18n_$id" | tr '.' '_' | tr '-' '_' )
    printf "    %s string = \"%s\"\n" "$const_name" "$id"
  done

  echo ")"
} > "$OUTPUT_FILE"