//go:generate bash ./generate_constants.sh ./locales/ru.toml ./i18n_consts.go
// Code generated by generate_constants.sh. DO NOT EDIT.

package replyme

const (
	i18n_cmd_input_command           string = "cmd_input_command"
	i18n_cmd_input_running           string = "cmd_input_running"
	i18n_confirm_view_yes            string = "confirm_view_yes"
	i18n_confirm_view_no             string = "confirm_view_no"
	i18n_locales_message_notfound    string = "locales_message_notfound"
	i18n_inputfile_placeholder       string = "inputfile_placeholder"
	i18n_inputfile_fullpath_error    string = "inputfile_fullpath_error"
	i18n_inputfile_file_notfound     string = "inputfile_file_notfound"
	i18n_inputfile_extension_error   string = "inputfile_extension_error"
	i18n_inputfile_size_error        string = "inputfile_size_error"
	i18n_inputfile_read_error        string = "inputfile_read_error"
	i18n_inputfile_success           string = "inputfile_success"
	i18n_inputfile_path_error        string = "inputfile_path_error"
	i18n_parser_empty_command        string = "parser_empty_command"
	i18n_inputint_placeholder        string = "inputint_placeholder"
	i18n_help_flags                  string = "help_flags"
	i18n_help_subcommands            string = "help_subcommands"
	i18n_help_arguments              string = "help_arguments"
	i18n_help_authors                string = "help_authors"
	i18n_help_license                string = "help_license"
	i18n_help_flag_type_string       string = "help_flag_type_string"
	i18n_help_flag_type_int          string = "help_flag_type_int"
	i18n_help_flag_type_bool         string = "help_flag_type_bool"
	i18n_help_flag_type_string_array string = "help_flag_type_string_array"
	i18n_help_flag_type_int_array    string = "help_flag_type_int_array"
	i18n_app_help_usage              string = "app_help_usage"
	i18n_tui_selectone_item          string = "tui_selectone_item"
	i18n_tui_selectone_items         string = "tui_selectone_items"
	i18n_tui_inputFile_err           string = "tui_inputFile_err"
)
