//go:generate bash ./generate_constants.sh ./locales/ru.toml ./i18n_consts.go
// Code generated by generate_constants.sh. DO NOT EDIT.

package replyme

const (
	i18n_cmd_input_command string = "cmd_input_command"
)
